server:
  port: 8082

spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
  ai:
    alibaba:
      redis:
        chat-memory:
          enabled: true
          prefix: "chat_memory:"
    openai:
      api-key: sk-64a2c78c9be846dd9bbd3a1ebd89678d
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
